# Generated by Django 4.1.5 on 2023-01-10 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_comment_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                default="Change me", help_text="Description of the category"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="hex_color_code",
            field=models.CharField(
                default="000000",
                help_text="The 6 digit hex color code for the category background (https://htmlcolorcodes.com/)",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bid",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Bid creation time"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                help_text="Related listing",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.PositiveIntegerField(help_text="Bid price"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                help_text="Related user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(help_text="Category name", max_length=200),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Comment creation time"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                help_text="Related listing",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(help_text="Comment text"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                help_text="Related user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is this item still eavailable?"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                help_text="Which category best describes your item?",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="completed",
            field=models.BooleanField(default=False, help_text="Was this item sold?"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When was this item listing created?"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(
                help_text="How would you descibe your item? (500 characters maximum)",
                max_length=540,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                help_text="Do you have a photo of your item?", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.PositiveIntegerField(
                help_text="What would you like to start the item price at (Whole dollars only)"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(
                help_text="What would you like to offer to sell? (50 characters maximum)",
                max_length=53,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When was this item listing last updated?"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                help_text="Who are you?",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
