# Generated by Django 4.1.5 on 2023-01-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_category_description_category_hex_color_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="Change me",
                help_text="An icon representing the category from the list of available Bootstrap icons",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
