# Generated by Django 4.1.5 on 2023-01-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Do you have a photo of your item?",
                upload_to="images/",
            ),
        ),
    ]
