# Generated by Django 4.1.5 on 2023-01-11 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                help_text="Relationship between users and listings",
                related_name="watching",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
