# Generated by Django 4.1.5 on 2023-01-11 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.PositiveIntegerField(
                help_text="Bid price",
                validators=[
                    django.core.validators.MaxValueValidator(100000),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
